# Generated by Django 5.1.4 on 2024-12-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id_pengunjung', models.AutoField(primary_key=True, serialize=False)),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_belakang', models.CharField(max_length=50)),
                ('pekerjaan', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pengunjung',
                'verbose_name_plural': 'Pengunjung',
            },
        ),
        migrations.CreateModel(
            name='Roti',
            fields=[
                ('id_roti', models.AutoField(primary_key=True, serialize=False)),
                ('nama_roti', models.CharField(max_length=100)),
                ('varian_rasa', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Roti',
            },
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id_toko', models.AutoField(primary_key=True, serialize=False)),
                ('nama_toko', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('stok_roti', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Toko',
            },
        ),
        migrations.CreateModel(
            name='Memesan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_roti', models.IntegerField()),
                ('totalHarga', models.PositiveIntegerField(default=0, verbose_name='Total Harga')),
                ('id_pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.pengunjung')),
            ],
            options={
                'verbose_name': 'Memesan',
                'verbose_name_plural': 'Memesan',
            },
        ),
        migrations.CreateModel(
            name='DetailMemesan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetail')),
                ('idMemesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.memesan', verbose_name='idMemesan')),
                ('idRoti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.roti', verbose_name='idRoti')),
            ],
            options={
                'verbose_name': 'Detail Memesan',
                'verbose_name_plural': 'Detail Memesan',
            },
        ),
        migrations.CreateModel(
            name='TokoMemilikiRoti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_roti', models.IntegerField(verbose_name='Jumlah Roti')),
                ('id_toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.toko')),
            ],
            options={
                'verbose_name': 'Toko Memiliki Roti',
                'verbose_name_plural': 'Toko Memiliki Roti',
            },
        ),
        migrations.CreateModel(
            name='DetailTokoRoti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetail')),
                ('idRoti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.roti', verbose_name='idRoti')),
                ('idTokoRoti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.tokomemilikiroti', verbose_name='idTokoRoti')),
            ],
            options={
                'verbose_name': 'Detail Toko Roti',
                'verbose_name_plural': 'Detail Toko Roti',
            },
        ),
    ]
