# Generated by Django 5.1.2 on 2024-12-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengunjung',
            name='id_toko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesanan.toko'),
        ),
    ]
